version: v1
project: yay
services:
  default:
    redis:
      image: redis:latest
      instances: 1
      mem: 128
      volumes:
        - container_path: /data
          size: 8GB
    mysql:
      image: mysql:5.7
      instances: 1
      mem: 512
      env:
        - MYSQL_ROOT_PASSWORD: root
        - MYSQL_DATABASE: default
      volumes:
        - container_path: /var/lib/mysql
          size: 8GB
    web:
      image: sveneisenschmidt/yay:stable
      instances: 1
      mem: 128
      domain: $URI
      port: 80
      dependencies:
        - ../default/mysql
        - ../default/redis
        - ../default/install
      env:
        - APP_MODE: web
        - APP_ENV: prod
        - DATABASE_HOST: mysql.default.yay
        - DATABASE_NAME: default
        - DATABASE_USER: root
        - DATABASE_PASSWORD: root
        - REDIS_HOST: redis.default.yay
        - REDIS_PORT: "6379"
    install:
      image: sveneisenschmidt/yay:stable
      instances: 1
      mem: 128
      dependencies:
        - ../default/mysql
        - ../default/redis
      env:
        - APP_MODE: install
        - APP_ENV: prod
        - DATABASE_HOST: mysql.default.yay
        - DATABASE_NAME: default
        - DATABASE_USER: root
        - DATABASE_PASSWORD: root
        - REDIS_HOST: redis.default.yay
        - REDIS_PORT: "6379"
    